-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accesorios
(
    id serial NOT NULL,
    producto_id integer NOT NULL,
    subtipo_accesorio character varying(100) COLLATE pg_catalog."default" NOT NULL,
    talla character varying(20) COLLATE pg_catalog."default",
    color character varying(50) COLLATE pg_catalog."default",
    material character varying(100) COLLATE pg_catalog."default",
    marca character varying(100) COLLATE pg_catalog."default",
    certificacion character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT accesorios_pkey PRIMARY KEY (id),
    CONSTRAINT accesorios_producto_id_key UNIQUE (producto_id)
);

CREATE TABLE IF NOT EXISTS public.alertas_stock
(
    id serial NOT NULL,
    producto_id integer,
    tipo_alerta character varying(20) COLLATE pg_catalog."default",
    stock_actual integer NOT NULL,
    stock_minimo integer NOT NULL,
    leida boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT alertas_stock_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bitacora_sistema
(
    id serial NOT NULL,
    usuario_id integer,
    accion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tabla_afectada character varying(50) COLLATE pg_catalog."default",
    registro_id integer,
    detalles jsonb,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bitacora_sistema_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado boolean DEFAULT true,
    tipo_producto_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categorias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id serial NOT NULL,
    cedula_rif character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre_completo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    telefono_principal character varying(15) COLLATE pg_catalog."default",
    telefono_alternativo character varying(15) COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    fecha_registro date DEFAULT CURRENT_DATE,
    estado boolean DEFAULT true,
    usuario_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clientes_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_cedula_rif_key UNIQUE (cedula_rif)
);

CREATE TABLE IF NOT EXISTS public.compras
(
    id serial NOT NULL,
    codigo_compra character varying(20) COLLATE pg_catalog."default" NOT NULL,
    proveedor_id integer,
    usuario_id integer,
    subtotal numeric(10, 2) NOT NULL,
    iva numeric(10, 2) DEFAULT 0,
    total numeric(10, 2) NOT NULL,
    estado_compra character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    fecha_estimada_entrega date,
    observaciones text COLLATE pg_catalog."default",
    activa boolean DEFAULT true,
    notas_incidencia text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    moneda_factura character varying(3) COLLATE pg_catalog."default" DEFAULT 'USD'::character varying,
    tasa_cambio numeric(12, 4),
    monto_bs numeric(12, 2),
    monto_usd numeric(12, 2),
    moneda_pago character varying(10) COLLATE pg_catalog."default" DEFAULT 'USD'::character varying,
    metodo_pago_id integer,
    CONSTRAINT compras_pkey PRIMARY KEY (id),
    CONSTRAINT compras_codigo_compra_key UNIQUE (codigo_compra)
);

CREATE TABLE IF NOT EXISTS public.configuracion_integraciones
(
    clave character varying(80) COLLATE pg_catalog."default" NOT NULL,
    valor text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT configuracion_integraciones_pkey PRIMARY KEY (clave)
);

CREATE TABLE IF NOT EXISTS public.detalle_compras
(
    id serial NOT NULL,
    compra_id integer,
    producto_id integer,
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    precio_unitario_bs numeric(12, 2),
    precio_unitario_usd numeric(12, 2),
    CONSTRAINT detalle_compras_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detalle_pedidos_online
(
    id serial NOT NULL,
    pedido_id integer,
    producto_id integer,
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT detalle_pedidos_online_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detalle_ventas
(
    id serial NOT NULL,
    venta_id integer,
    producto_id integer,
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    precio_unitario_bs numeric(12, 2),
    precio_unitario_usd numeric(12, 2),
    CONSTRAINT detalle_ventas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.devoluciones
(
    id serial NOT NULL,
    codigo_devolucion character varying(20) COLLATE pg_catalog."default" NOT NULL,
    venta_id integer,
    pedido_id integer,
    cliente_id integer,
    producto_id integer,
    cantidad integer NOT NULL,
    motivo text COLLATE pg_catalog."default" NOT NULL,
    estado_devolucion character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    tipo_reintegro character varying(20) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT devoluciones_pkey PRIMARY KEY (id),
    CONSTRAINT devoluciones_codigo_devolucion_key UNIQUE (codigo_devolucion)
);

CREATE TABLE IF NOT EXISTS public.empresa_configuracion
(
    id serial NOT NULL,
    nombre_empresa character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rif character varying(20) COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default",
    telefono character varying(15) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    iva_porcentaje numeric(5, 2) DEFAULT 16.00,
    actualizado_por integer,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT empresa_configuracion_pkey PRIMARY KEY (id),
    CONSTRAINT empresa_configuracion_rif_key UNIQUE (rif)
);

CREATE TABLE IF NOT EXISTS public.incidencias_soporte
(
    id serial NOT NULL,
    codigo_incidencia character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cliente_id integer,
    usuario_id integer,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    urgencia character varying(20) COLLATE pg_catalog."default" DEFAULT 'media'::character varying,
    modulo_sistema character varying(50) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'pendiente'::character varying,
    asignado_a integer,
    notas_solucion text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT incidencias_soporte_pkey PRIMARY KEY (id),
    CONSTRAINT incidencias_soporte_codigo_incidencia_key UNIQUE (codigo_incidencia)
);

CREATE TABLE IF NOT EXISTS public.metodos_pago
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    moneda character varying(10) COLLATE pg_catalog."default" DEFAULT 'AMBOS'::character varying,
    CONSTRAINT metodos_pago_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.metodos_pago_reservas
(
    id serial NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    banco character varying(100) COLLATE pg_catalog."default",
    cedula character varying(20) COLLATE pg_catalog."default",
    telefono character varying(15) COLLATE pg_catalog."default",
    numero_cuenta character varying(50) COLLATE pg_catalog."default",
    codigo_banco character varying(10) COLLATE pg_catalog."default",
    estado boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT metodos_pago_reservas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movimientos_inventario
(
    id serial NOT NULL,
    producto_id integer,
    tipo_movimiento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cantidad integer NOT NULL,
    stock_anterior integer NOT NULL,
    stock_actual integer NOT NULL,
    motivo text COLLATE pg_catalog."default",
    referencia character varying(100) COLLATE pg_catalog."default",
    usuario_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movimientos_inventario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notificaciones_vendedor
(
    id serial NOT NULL,
    pedido_id integer NOT NULL,
    titulo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    mensaje text COLLATE pg_catalog."default",
    tipo character varying(40) COLLATE pg_catalog."default" DEFAULT 'pedido'::character varying,
    leida boolean DEFAULT false,
    usuario_id integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT notificaciones_vendedor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pedidos_online
(
    id serial NOT NULL,
    codigo_pedido character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cliente_id integer,
    subtotal numeric(10, 2) NOT NULL,
    iva numeric(10, 2) DEFAULT 0,
    total numeric(10, 2) NOT NULL,
    estado_pedido character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    metodo_pago_id integer,
    direccion_entrega text COLLATE pg_catalog."default",
    telefono_contacto character varying(15) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    canal_comunicacion character varying(30) COLLATE pg_catalog."default" DEFAULT 'whatsapp'::character varying,
    tipo_entrega character varying(20) COLLATE pg_catalog."default" DEFAULT 'tienda'::character varying,
    referencia_pago text COLLATE pg_catalog."default",
    vendedor_asignado_id integer,
    fecha_asignacion timestamp without time zone,
    fecha_contacto timestamp without time zone,
    fecha_pago timestamp without time zone,
    intentos_contacto integer DEFAULT 0,
    venta_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    comprobante_url character varying(500) COLLATE pg_catalog."default",
    metodo_pago character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT pedidos_online_pkey PRIMARY KEY (id),
    CONSTRAINT pedidos_online_codigo_pedido_key UNIQUE (codigo_pedido)
);

CREATE TABLE IF NOT EXISTS public.producto_imagenes
(
    id serial NOT NULL,
    producto_id integer NOT NULL,
    imagen_url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    es_principal boolean DEFAULT false,
    orden integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT producto_imagenes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.producto_promociones
(
    id serial NOT NULL,
    producto_id integer,
    promocion_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT producto_promociones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.producto_proveedor
(
    id serial NOT NULL,
    producto_id integer NOT NULL,
    proveedor_id integer NOT NULL,
    precio_compra numeric(10, 2) NOT NULL,
    sku_proveedor character varying(50) COLLATE pg_catalog."default",
    tiempo_entrega_dias integer,
    es_principal boolean DEFAULT false,
    activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT producto_proveedor_pkey PRIMARY KEY (id),
    CONSTRAINT producto_proveedor_producto_id_proveedor_id_key UNIQUE (producto_id, proveedor_id)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id serial NOT NULL,
    codigo_interno character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    categoria_id integer,
    precio_compra numeric(10, 2) NOT NULL,
    precio_venta numeric(10, 2) NOT NULL,
    stock_actual integer DEFAULT 0,
    stock_minimo integer DEFAULT 5,
    stock_maximo integer DEFAULT 100,
    proveedor_id integer,
    estado boolean DEFAULT true,
    tipo_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    moneda_base character varying(3) COLLATE pg_catalog."default" DEFAULT 'USD'::character varying,
    precio_venta_bs numeric(12, 2),
    precio_venta_usd numeric(12, 2),
    precio_compra_bs numeric(12, 2),
    precio_compra_usd numeric(12, 2),
    stock_reservado integer DEFAULT 0,
    CONSTRAINT productos_pkey PRIMARY KEY (id),
    CONSTRAINT productos_codigo_interno_key UNIQUE (codigo_interno)
);

CREATE TABLE IF NOT EXISTS public.promociones
(
    id serial NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    tipo_promocion character varying(20) COLLATE pg_catalog."default",
    valor numeric(10, 2),
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    estado boolean DEFAULT true,
    imagen_url character varying(500) COLLATE pg_catalog."default",
    tipo_imagen character varying(20) COLLATE pg_catalog."default" DEFAULT 'auto'::character varying,
    imagen_banco_key character varying(50) COLLATE pg_catalog."default",
    color_personalizado character varying(20) COLLATE pg_catalog."default" DEFAULT '#1F9166'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT promociones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    id serial NOT NULL,
    razon_social character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rif character varying(20) COLLATE pg_catalog."default" NOT NULL,
    persona_contacto character varying(100) COLLATE pg_catalog."default",
    telefono_principal character varying(15) COLLATE pg_catalog."default",
    telefono_alternativo character varying(15) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    productos_suministrados text COLLATE pg_catalog."default",
    estado boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT proveedores_pkey PRIMARY KEY (id),
    CONSTRAINT proveedores_rif_key UNIQUE (rif)
);

CREATE TABLE IF NOT EXISTS public.repuestos
(
    id serial NOT NULL,
    producto_id integer NOT NULL,
    categoria_tecnica character varying(100) COLLATE pg_catalog."default" NOT NULL,
    marca_compatible character varying(100) COLLATE pg_catalog."default",
    modelo_compatible character varying(100) COLLATE pg_catalog."default",
    anio_compatible character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT repuestos_pkey PRIMARY KEY (id),
    CONSTRAINT repuestos_producto_id_key UNIQUE (producto_id)
);

CREATE TABLE IF NOT EXISTS public.reservas
(
    id serial NOT NULL,
    codigo_reserva character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cliente_id integer,
    producto_id integer,
    cantidad integer NOT NULL,
    fecha_reserva date NOT NULL,
    fecha_limite date NOT NULL,
    estado_reserva character varying(20) COLLATE pg_catalog."default" DEFAULT 'ACTIVA'::character varying,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    monto_adelanto numeric(12, 2) DEFAULT 0,
    fecha_cuota date,
    monto_restante numeric(12, 2) DEFAULT 0,
    estado_pago character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    referencia_pago character varying(50) COLLATE pg_catalog."default",
    metodo_pago character varying(50) COLLATE pg_catalog."default",
    fecha_pago timestamp without time zone,
    comprobante_url text COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    metodo_pago_resto character varying(100) COLLATE pg_catalog."default",
    referencia_pago_resto character varying(100) COLLATE pg_catalog."default",
    comprobante_url_resto text COLLATE pg_catalog."default",
    monto_pagado_resto numeric(12, 2) DEFAULT 0,
    fecha_pago_resto timestamp without time zone,
    subtotal numeric(12, 2) DEFAULT 0,
    iva numeric(12, 2) DEFAULT 0,
    monto_total numeric(12, 2) DEFAULT 0,
    CONSTRAINT reservas_pkey PRIMARY KEY (id),
    CONSTRAINT reservas_codigo_reserva_key UNIQUE (codigo_reserva)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    permisos jsonb,
    estado boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.seguimiento_incidencias
(
    id serial NOT NULL,
    incidencia_id integer NOT NULL,
    usuario_id integer,
    accion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT seguimiento_incidencias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tasas_cambio
(
    id serial NOT NULL,
    tasa numeric(12, 4) NOT NULL,
    moneda_origen character varying(3) COLLATE pg_catalog."default" DEFAULT 'USD'::character varying,
    moneda_destino character varying(3) COLLATE pg_catalog."default" DEFAULT 'VES'::character varying,
    fecha_vigencia date NOT NULL,
    usuario_id integer,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tasas_cambio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipos_producto
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tipos_producto_pkey PRIMARY KEY (id),
    CONSTRAINT tipos_producto_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombre_completo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rol_id integer,
    cliente_id integer,
    estado boolean DEFAULT true,
    ultimo_acceso timestamp without time zone,
    intentos_fallidos integer DEFAULT 0,
    bloqueado_hasta timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email),
    CONSTRAINT usuarios_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.vehiculos
(
    id serial NOT NULL,
    producto_id integer NOT NULL,
    marca character varying(100) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    anio character varying(4) COLLATE pg_catalog."default",
    cilindrada character varying(50) COLLATE pg_catalog."default",
    color character varying(50) COLLATE pg_catalog."default",
    kilometraje integer DEFAULT 0,
    tipo_vehiculo character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vehiculos_pkey PRIMARY KEY (id),
    CONSTRAINT vehiculos_producto_id_key UNIQUE (producto_id)
);

CREATE TABLE IF NOT EXISTS public.venta_pagos
(
    id serial NOT NULL,
    venta_id integer NOT NULL,
    metodo_pago_id integer,
    metodo_nombre character varying(200) COLLATE pg_catalog."default",
    moneda character varying(10) COLLATE pg_catalog."default" DEFAULT 'BS'::character varying,
    monto numeric(14, 2) DEFAULT 0,
    monto_bs numeric(14, 2) DEFAULT 0,
    monto_usd numeric(14, 2) DEFAULT 0,
    es_efectivo boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT venta_pagos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ventas
(
    id serial NOT NULL,
    codigo_venta character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cliente_id integer,
    usuario_id integer,
    metodo_pago_id integer,
    subtotal numeric(10, 2) NOT NULL,
    iva numeric(10, 2) DEFAULT 0,
    total numeric(10, 2) NOT NULL,
    estado_venta character varying(20) COLLATE pg_catalog."default" DEFAULT 'COMPLETADA'::character varying,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    moneda_pago character varying(3) COLLATE pg_catalog."default" DEFAULT 'USD'::character varying,
    tasa_cambio numeric(12, 4),
    monto_bs numeric(12, 2),
    monto_usd numeric(12, 2),
    CONSTRAINT ventas_pkey PRIMARY KEY (id),
    CONSTRAINT ventas_codigo_venta_key UNIQUE (codigo_venta)
);

ALTER TABLE IF EXISTS public.accesorios
    ADD CONSTRAINT accesorios_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS accesorios_producto_id_key
    ON public.accesorios(producto_id);


ALTER TABLE IF EXISTS public.alertas_stock
    ADD CONSTRAINT alertas_stock_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bitacora_sistema
    ADD CONSTRAINT bitacora_sistema_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bitacora_usuario
    ON public.bitacora_sistema(usuario_id);


ALTER TABLE IF EXISTS public.categorias
    ADD CONSTRAINT categorias_tipo_producto_id_fkey FOREIGN KEY (tipo_producto_id)
    REFERENCES public.tipos_producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT fk_cliente_usuario FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras
    ADD CONSTRAINT compras_metodo_pago_id_fkey FOREIGN KEY (metodo_pago_id)
    REFERENCES public.metodos_pago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras
    ADD CONSTRAINT compras_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras
    ADD CONSTRAINT compras_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_compras
    ADD CONSTRAINT detalle_compras_compra_id_fkey FOREIGN KEY (compra_id)
    REFERENCES public.compras (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_compras
    ADD CONSTRAINT detalle_compras_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_pedidos_online
    ADD CONSTRAINT detalle_pedidos_online_pedido_id_fkey FOREIGN KEY (pedido_id)
    REFERENCES public.pedidos_online (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.detalle_pedidos_online
    ADD CONSTRAINT detalle_pedidos_online_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_ventas
    ADD CONSTRAINT detalle_ventas_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_ventas
    ADD CONSTRAINT detalle_ventas_venta_id_fkey FOREIGN KEY (venta_id)
    REFERENCES public.ventas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.devoluciones
    ADD CONSTRAINT devoluciones_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.devoluciones
    ADD CONSTRAINT devoluciones_pedido_id_fkey FOREIGN KEY (pedido_id)
    REFERENCES public.pedidos_online (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.devoluciones
    ADD CONSTRAINT devoluciones_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.devoluciones
    ADD CONSTRAINT devoluciones_venta_id_fkey FOREIGN KEY (venta_id)
    REFERENCES public.ventas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.incidencias_soporte
    ADD CONSTRAINT incidencias_soporte_asignado_a_fkey FOREIGN KEY (asignado_a)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_incidencias_asignado
    ON public.incidencias_soporte(asignado_a);


ALTER TABLE IF EXISTS public.incidencias_soporte
    ADD CONSTRAINT incidencias_soporte_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_incidencias_cliente
    ON public.incidencias_soporte(cliente_id);


ALTER TABLE IF EXISTS public.incidencias_soporte
    ADD CONSTRAINT incidencias_soporte_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimientos_inventario
    ADD CONSTRAINT movimientos_inventario_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_inventario_producto
    ON public.movimientos_inventario(producto_id);


ALTER TABLE IF EXISTS public.notificaciones_vendedor
    ADD CONSTRAINT notificaciones_vendedor_pedido_id_fkey FOREIGN KEY (pedido_id)
    REFERENCES public.pedidos_online (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notificaciones_vendedor
    ADD CONSTRAINT notificaciones_vendedor_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pedidos_online
    ADD CONSTRAINT pedidos_online_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_pedidos_cliente
    ON public.pedidos_online(cliente_id);


ALTER TABLE IF EXISTS public.pedidos_online
    ADD CONSTRAINT pedidos_online_metodo_pago_id_fkey FOREIGN KEY (metodo_pago_id)
    REFERENCES public.metodos_pago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedidos_online
    ADD CONSTRAINT pedidos_online_vendedor_id_fkey FOREIGN KEY (vendedor_asignado_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.producto_imagenes
    ADD CONSTRAINT producto_imagenes_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_producto_imagenes_producto
    ON public.producto_imagenes(producto_id);


ALTER TABLE IF EXISTS public.producto_promociones
    ADD CONSTRAINT producto_promociones_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto_promociones
    ADD CONSTRAINT producto_promociones_promocion_id_fkey FOREIGN KEY (promocion_id)
    REFERENCES public.promociones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto_proveedor
    ADD CONSTRAINT producto_proveedor_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.producto_proveedor
    ADD CONSTRAINT producto_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT productos_categoria_id_fkey FOREIGN KEY (categoria_id)
    REFERENCES public.categorias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_productos_categoria
    ON public.productos(categoria_id);


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT productos_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT productos_tipo_id_fkey FOREIGN KEY (tipo_id)
    REFERENCES public.tipos_producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.repuestos
    ADD CONSTRAINT repuestos_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS repuestos_producto_id_key
    ON public.repuestos(producto_id);


ALTER TABLE IF EXISTS public.reservas
    ADD CONSTRAINT reservas_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reservas
    ADD CONSTRAINT reservas_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seguimiento_incidencias
    ADD CONSTRAINT seguimiento_incidencias_incidencia_id_fkey FOREIGN KEY (incidencia_id)
    REFERENCES public.incidencias_soporte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_seguimiento_incidencia
    ON public.seguimiento_incidencias(incidencia_id);


ALTER TABLE IF EXISTS public.seguimiento_incidencias
    ADD CONSTRAINT seguimiento_incidencias_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_usuarios_rol
    ON public.usuarios(rol_id);


ALTER TABLE IF EXISTS public.vehiculos
    ADD CONSTRAINT vehiculos_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS vehiculos_producto_id_key
    ON public.vehiculos(producto_id);


ALTER TABLE IF EXISTS public.venta_pagos
    ADD CONSTRAINT venta_pagos_metodo_pago_id_fkey FOREIGN KEY (metodo_pago_id)
    REFERENCES public.metodos_pago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta_pagos
    ADD CONSTRAINT venta_pagos_venta_id_fkey FOREIGN KEY (venta_id)
    REFERENCES public.ventas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_venta_pagos_venta_id
    ON public.venta_pagos(venta_id);


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_metodo_pago_id_fkey FOREIGN KEY (metodo_pago_id)
    REFERENCES public.metodos_pago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;